services:
  app:
    container_name: QueueFlow
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        UID: ${UID}
        GID: ${GID}
        USER: appuser
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./:/app
      - ./docker/php/custom_dev.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./docker/caddy/Caddyfile.dev:/etc/caddy/Caddyfile
    depends_on:
      - db
    networks:
      - queue_flow_network

  db:
    container_name: QueueFlowDB
    image: postgres:17.6
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --lc-collate=C --lc-ctype=C"
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "${DB_PORT:-5432}:5432"
    networks:
      - queue_flow_network

volumes:
  db:
    driver: local

networks:
  queue_flow_network:
    driver: bridge
